server:
  port: 8083
spring:
  datasource:
    username: postgres
    password: 08102003
    url: jdbc:postgresql://localhost:5432/secure
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
